---
- name: Mesos test cluster bootstrapper.  Master, slave, zookeeper.
  hosts: mesos
  remote_user: ubuntu
  become: yes
  become_method: sudo
  # don't forget ansible-playbook "ask" options on first run: -k -K

  vars:
    user: "ubuntu"
    key_file: "~/.ssh/id_boot2docker.pub"
    zk_quorum: "{{ (((play_hosts | length) + 1) / 2 ) | round | int }}"

  roles:
    - auth
    - install
    - config
