---
- name: Mesos test cluster bootstrapper.  Master, slave, zookeeper.
  hosts: mesos
  remote_user: ubuntu
  become: yes
  become_method: sudo
  # don't forget ansible-playbook "ask" options: -k -K

  vars:
    user: "ubuntu"
    key_file: "~/.ssh/id_boot2docker.pub"
    zk_id: 1
    zookeeper_hosts:
      - host: "{{ inventory_hostname }}"
        id: 1
      - host: "{{ inventory_hostname }}"
        id: 2
      - host: "{{ inventory_hostname }}"
        id: 3

  roles:
    - auth
    - install
    - config
