---

- name: set zookeeper myid
  template:
    src: myid.j2
    dest: /etc/zookeeper/conf/myid
  notify:
    - restart zookeeper

- name: set zoo.conf
  template:
    src: zoo.cfg.j2
    dest: /etc/zookeeper/conf/zoo.cfg
  notify:
    - restart zookeeper

- name: set mesos zk
  template:
    src: zk.j2
    dest: /etc/mesos/zk

- name: set mesos quorum size
  template:
    src: quorum.j2
    dest: /etc/mesos-master/quorum

- name: create hostname directories
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  with_items:
    - /etc/mesos-master
    - /etc/marathon/conf

- name: set hostname files
  template:
    src: hostname.j2
    dest: "{{ item }}"
  with_items:
    - /etc/mesos-master/hostname
    - /etc/marathon/conf/hostname
  notify:
    - restart mesos-master
    - restart mesos-slave
    - restart marathon

- name: ensure services are up
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - zookeeper
    - mesos-master
    - mesos-slave
    - marathon
