---

- name: set zookeeper myid
  template:
    src: myid.j2
    dest: /etc/zookeeper/conf/myid
  notify:
    - restart zookeeper

- name: set zoo.conf
  template:
    src: zoo.cfg.j2
    dest: /etc/zookeeper/conf/zoo.cfg
  notify:
    - restart zookeeper
