---

- name: add docker apt key
  apt_key:
    keyserver: p80.pool.sks-keyservers.net
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: add docker repo
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: install docker-engine
  apt:
    pkg: docker-engine
    state: present
    update_cache: yes

- name: ensure docker is up
  service:
    name: docker
    state: started

- name: add user to docker group
  user:
    name: "{{ user }}"
    groups: "docker"
    append: yes

- name: add the docker containerizer
  template:
    src: containerizers.j2
    dest: /etc/mesos-slave/containerizers

- name: set marathon executor timeout
  template:
    src: executor_registration_timeout.j2
    dest: /etc/mesos-slave/executor_registration_timeout
